### ISSUE TITLE
Staking tx status stuck at DELEGATION_ACTIVE

### ISSUE THREAD

**Issue by gitferry** [babylonlabs-io/btc-staker#18]
After an unbonding tx collects sufficient covenant signatures, the related staking tx's status will be changed to `DELEGATION_ACTIVE` and send the unbonding tx to BTC.

If the staker daemon is terminated at this moment, it will loose the even for unbonding tx got confirmed on BTC. Therefore the status of the related staking tx will stuck at `DELEGATION_ACTIVE` and users cannot withdraw.

**Comment by KonradStaniec** [comment]
closed by: https://github.com/babylonlabs-io/btc-staker/pull/20
